---
- name: Ensure all required variables are defined before configuring the monitoring system
  assert:
    that:
      - monitoring_email_addresses is defined
      - mysql_root_password is defined
      - monitoring_db_user is defined
      - monitoring_db_name is defined
      - monitoring_db_password is defined
      - monitoring_db_web_user is defined
      - monitoring_db_web_name is defined
      - monitoring_db_web_password is defined
      - icinga_admin_password is defined
      - icinga_salt is defined
      - icinga_api_password is defined
  when: groups['all'] | length() == 1 or inventory_hostname in groups['monitoring']

- name: Add icinga2 key for repository
  shell: wget -O - https://packages.icinga.com/icinga.key | apt-key add
  when: not offline_mode.stat.exists

- name: Add icinga2 repository
  apt_repository:
    repo: deb https://packages.icinga.com/debian icinga-{{ ansible_distribution_release }} main
    state: present
    filename: icinga2
    update_cache: yes
  when: not offline_mode.stat.exists

- name: Install Icinga2 and monitoring plugins
  apt: name={{ item }} state=present
  with_items:
    - icinga2
    - monitoring-plugins
    - nagios-plugins-contrib
    - libredis-perl
    - libmonitoring-plugin-perl
    - liblwp-useragent-determined-perl
    - libdbd-mysql-perl
  check_mode: no

- name: Clear plugin directory
  block:
    - name: Determine plugin directory content
      find:
        path: /usr/share/icinga2/include/plugins-contrib.d
        file_type: any
        hidden: yes
      register: plugin_dir_content
    - name: Delete plugin directory content
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ plugin_dir_content.files }}"
      loop_control:
        label: "{{ item.path }}"

- name: Enable and start the icinga2 daemon
  service: name=icinga2 state=started enabled=true

- name: Install additional icinga plugins
  copy:
    src: "{{ item }}"
    dest: /usr/lib/nagios/plugins
    mode: 0755
  with_fileglob:
    - "files/checks/*"

- name: Configure Icinga2 commands
  copy: src=commands.conf dest=/etc/icinga2/conf.d
  notify: restart icinga2

- name: Ensure sudo is installed
  apt:
    pkg: sudo
    state: present

- name: Set sudo escalation for icinga plugins
  lineinfile:
    dest: /etc/sudoers
    line: "nagios ALL=(root) NOPASSWD: /usr/lib/nagios/plugins/"
    state: present
    validate: '/usr/sbin/visudo -cf %s'

- name: Configure Icinga NodeName
  lineinfile:
    dest: /etc/icinga2/constants.conf
    regexp: "^//const NodeName = \"localhost\"$"
    line: "const NodeName = \"{{ inventory_hostname }}\""
    backrefs: yes
  notify: restart icinga2

- name: Fix Icinga PKI directory permissions
  file: dest=/etc/icinga2/pki owner=nagios group=nagios mode=0750

- name: Download check_ntp_time from repo.teamwire.eu
  get_url:
    url: https://repo.teamwire.eu/bin/icinga/check_ntp_time
    dest: /usr/lib/nagios/plugins/check_ntp_time
     
- include: "database-configuration.yml"
  when: mysql_root_password is defined

- include: "master.yml"
  when: groups['all'] | length() == 1 or inventory_hostname in groups['monitoring']

- include: "client.yml"


