---
- name: Install Redis
  apt: name={{ item }} state=present
  with_items:
  - redis-tools
  - python3-redis
  - redis-server

# See http://redis.io/topics/faq for details
- name: Enable vm.overcommit_memory for Redis
  sysctl:
    name: vm.overcommit_memory
    value: "1"
    state: present
    reload: true

- name: Increase number of socket connection backlog
  sysctl:
    name: net.core.somaxconn
    value: "1024"
    state: present
    reload: true

- name: Remove redis-cli history files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/home/teamwire/.rediscli_history"
    - "/root/.rediscli_history"

- name: Disable redis-cli history
  lineinfile:
    dest: /etc/environment
    line: "REDISCLI_HISTFILE=/dev/null"

- include_tasks: single.yml
  when: "'redis_servers' not in groups"

- include_tasks: cluster.yml
  when: "'redis_servers' in groups"
