---
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - Ansible lint
  - Shell check
  - Golint

default:
  tags:
    - desktop
    - linux

# --- ANSIBLE LINT TEST ---- #

Single server test:
  stage: Ansible lint
  script:
    - ansible-lint ./ansible/site.yml -x 301 --force-color

Cluster server test:
  stage: Ansible lint
  script:
    - ansible-lint ./ansible/playbooks/cluster.yml -x 301 --force-color

Procedure test:
  stage: Ansible lint
  script:
    - ansible-lint ansible/playbooks/procedures/*.yml -x 301        --force-color

Roles dir test:
  stage: Ansible lint
  script:
    - ansible-lint ./ansible/playbooks/roles/*.yml -x 301 --force-color

# ---SHELL CHECK TEST ---- #

Packer Build vmware test:
  stage: Shell check
  script:
    - shellcheck --format=tty --color=always ./packer/build-vmware.sh
  allow_failure: true

Packer network fix script test:
  stage: Shell check
  script:
    - shellcheck --format=tty --color=always ./packer/scripts/fix-network.sh
  allow_failure: true

Packer shrink test:
  stage: Shell check
  script:
    - shellcheck --format=tty --color=always ./packer/scripts/shrink-image.sh
  allow_failure: true

Packer offline image test:
  stage: Shell check
  script:
    - shellcheck --format=tty --color=always ./prepare-offline-installation.sh
  allow_failure: true

Packer unique test:
  stage: Shell check
  script:
    - shellcheck --format=tty --color=always ./packer/scripts/make-unique.sh
  allow_failure: true

Packer guest tools test:
  stage: Shell check
  script:
    - shellcheck --format=tty --color=always ./packer/scripts/vm-guest-tools.sh
  allow_failure: true

OCSP wrapper test:
  stage: Shell check
  script:
    - shellcheck --format=tty --color=always ./ansible/roles/frontend/files/ocsp.sh
  allow_failure: true

GIT wrapper test:
  stage: Shell check
  script:
    - shellcheck --format=tty --color=always ./ansible/roles/management/files/gitwrapper.sh
  allow_failure: true

Backup / Restore test:
  stage: Shell check
  script:
    - shellcheck --format=tty --color=always ./ansible/roles/db/files/backup_restore_db.sh
  allow_failure: true

Offline installation test:
  stage: Shell check
  script:
    - shellcheck --format=tty --color=always ./packer/scripts/prepare-offline-installation.sh
  allow_failure: true

TWCTL test:
  stage: Shell check
  script:
    - shellcheck --format=tty --color=always ./ansible/roles/management/files/twctl
  allow_failure: true

# --- GO LINT TEST --- #

OcspResonder test:
  stage: Golint
  script:
    - golint ./ansible/roles/go/files/ocspResponder.go
  allow_failure: true

Archiving test:
  stage: Golint
  script:
    - golint ./ansible/roles/go/files/archiving.go
  allow_failure: true
