---
stages:
  - release

default:
  tags:
    - platform
    - lint


release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+(\.\d+)?$/
      when: manual
    - if: $CI_COMMIT_TAG
      when: never
  script:
    - ls -la
    - git remote add github https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/csubeeteamwire/platform.git
    - git status
    - git branch
    - git remote -v
    - git push github $CI_COMMIT_TAG
    - git push github master
  after_script:
    - rm -rf .git
