---
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+(\.\d+)?$/
    
stages:
  - test
  - release

default:
  tags:
    - platform
    - lint

test:
  stage: test
  script:
    - pong
  allow_failure: true

release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+(\.\d+)?$/
      when: manual
    - if: $CI_COMMIT_TAG
      when: never

  script:
    - ls -la
    - git remote add github https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/csubeeteamwire/platform.git
    - git push github $CI_COMMIT_TAG
    - git fetch
    - git checkout master
    - git push github master
  after_script:
    - rm -rf .git
