---
- name: Ensure xtrabackup_password is configured before installing the Database
  fail: msg="Database replication user password is not defined. Please check the configuration file"
  when: xtrabackup_password is not defined or xtrabackup_password == None

- name: Remove Percona XtraBackup
  apt:
    name:
      - percona-xtrabackup-24
    state: absent

- name: Remove Percona repository
  file:
    path: /etc/apt/sources.list.d/repo_percona_com_apt.list
    state: absent

- name: Install Galera and requirements
  apt:
    name:
      - galera-{{ '3' if ansible_distribution_release == 'buster' else '4' }}
      - libconfig-inifiles-perl
      - libterm-readkey-perl
      - mariadb-backup
      - socat

- name: Create database replication user
  mysql_user:
    host: localhost
    name: mariabackup
    password: "{{ xtrabackup_password }}"
    priv: "*.*:RELOAD,LOCK TABLES,REPLICATION CLIENT,PROCESS"
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: inventory_hostname == groups['database_servers'][0]

- name: Write Galera cluster configuration
  template:
    src: cluster.conf.j2
    dest: /etc/mysql/conf.d/cluster.cnf
    mode: 0644

- name: Create clustercheck database user
  mysql_user:
    name: clustercheck
    host: localhost
    password: "{{ clustercheck_password }}"
    priv: "*.*:PROCESS"
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: inventory_hostname == groups['database_servers'][0]

# Clustercheck script from https://github.com/olafz/percona-clustercheck
# Licensed under the BSD license
- name: Install Galera cluster check script
  copy: src=clustercheck dest=/usr/local/bin/clustercheck mode=0755

- name: Copy systemd clustercheck socket configuration
  copy:
    src: clustercheck.socket
    dest: /etc/systemd/system/clustercheck.socket
    mode: 0640
  notify:
    - reload systemd

- name: Write systemd clustercheck service
  template:
    src: clustercheck@.service.j2
    dest: /etc/systemd/system/clustercheck@.service
    mode: 0644
  notify:
    - reload systemd

- name: Flush handlers
  meta: flush_handlers

- name: Enable the clustercheck service
  service: name=clustercheck.socket state=started enabled=true

- name: Register Galera servers with Consul
  template:
    src: consul-galera.hcl.j2
    dest: /etc/consul.d/galera.hcl
  notify: restart consul
