---
- name: Ensure mysql_root_password is configured before installing the Database
  fail: msg="MySQL root password is not defined. Please check the configuration file"
  when: config_done is defined and mysql_root_password is defined and mysql_root_password == None

- name: Check if installing a database cluster
  set_fact:
    galera_cluster: true
  when: '"database_servers" in groups and groups["database_servers"] | length > 1'

- name: Install MariaDB
  apt: name={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb-client
    - python3-mysqldb
  register: mysql_initial_installation

- name: Create MariaDB binlog directory
  file:
    dest: /var/lib/mysql-binlog
    owner: mysql
    group: mysql
    mode: 0770
    state: directory
  when: '"database_servers" not in groups'

# Install MariaDB server templates
# 50-server.cnf
# 60-teamwire.cnf
- include_tasks: server_templates.yml

- name: Set UTF8 as default character set
  copy:
    src: utf8.cnf
    dest: /etc/mysql/conf.d/utf8.cnf
  notify: restart MariaDB

- name: Set UTC as default time zone
  copy:
    src: timezone.cnf
    dest: /etc/mysql/conf.d/timezone.cnf
  notify: restart MariaDB

- name: Log slow queries
  copy:
    src: slow_query_log.cnf
    dest: /etc/mysql/conf.d/slow_query_log.cnf
  notify: restart MariaDB

- name: Disable unsecure functionality
  copy:
    src: security.cnf
    dest: /etc/mysql/conf.d/security.cnf
  notify: restart MariaDB

- name: Enable binary logs
  template:
    src: binlog.cnf.j2
    dest: /etc/mysql/conf.d/binlog.cnf
  notify: restart MariaDB
  when: '"database_servers" not in groups'

- name: Start and enable MariaDB server
  service: name=mysql state=started enabled=yes

# Make sure MariaDB is restarted before the database is created, otherwise
# the configured defaults are not used.
- name: Flush handlers
  meta: flush_handlers

- name: Set password for root user on MariaDB interfaces
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: "{{ item }}"
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: mysql_root_password is defined and (galera_cluster is not defined or inventory_hostname == groups['database_servers'][0])
  with_items:
    - 127.0.0.1
    - ::1
    - "{{ external_hostname|default() }}" # noqa var-spacing

- name: Create Teamwire database(s)
  mysql_db:
    name: "{{ item.value.dbname }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: true
  with_dict:
    - "{{ mysql_databases }}"
  when: galera_cluster is not defined or inventory_hostname == groups['database_servers'][0]

- name: Create Teamwire database user(s)
  mysql_user:
    name: "{{ item.value.username }}"
    host: "%"
    password: "{{ item.value.password }}"
    priv: "{{ item.value.dbname }}.*:ALL/*.*:RELOAD"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: true
  with_dict:
    - "{{ mysql_databases }}"
  when: config_done is defined and (galera_cluster is not defined or inventory_hostname == groups['database_servers'][0])

  # Ensure MariaDB UTC timezone definition is present
- name: Count MariaDB UTC timezone definition
  command: "mysql --defaults-file=/etc/mysql/debian.cnf -Bs -e 'SELECT COUNT(*) FROM time_zone_name WHERE name=\"UTC\";' mysql"
  changed_when: false
  register: mariadb_timezone_count
  check_mode: false

- name: Import MariaDB UTC timezone definition
  shell: "mysql_tzinfo_to_sql /usr/share/zoneinfo/UTC UTC | mysql --defaults-file=/etc/mysql/debian.cnf mysql" # noqa risky-shell-pipe
  when: mariadb_timezone_count.stdout == "0"

# Install database backup script
- include_tasks: backupscript.yml

- include_tasks: cluster.yml
  when: galera_cluster is defined

# ------------------------------------------------------------------------------
# Ensure mysql history is empty and disabled
# ------------------------------------------------------------------------------
- name: Remove mysql history files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/home/teamwire/.mysql_history"
    - "/root/.mysql_history"

- name: Disable mysql history
  ansible.builtin.lineinfile:
    dest: /etc/environment
    line: "MYSQL_HISTFILE=/dev/null"
