# This task will check if Vault has been initialized and read the secrets from there if so
- name: Vault Status check
  hosts: local:hashi_servers
  tasks:
    - name: Include vault role
      include_role:
        name: ../../roles/vault
        tasks_from: secrets
      when: ansible_local.vault is defined and ansible_local.vault.initialized == "true" and secrets_read is not defined

# This playbook applies to backend cluster nodes and the single server installation
- name: Configure the Teamwire backend server(s)
  hosts: backend_servers:voip_servers:stun_servers:local
  roles:
    - role: ../../roles/backend
