# This playbook applies to backend cluster nodes, not the single server installation
# The Hashi servers need to be run individually.
- hosts: hashi_servers
  serial: 1
  tasks:
    - name: Configure Consul on Hashi server nodes
      ansible.builtin.import_role:
        name: ../../roles/consul
      when: groups['all'] | length() > 1

- hosts: all:!hashi_servers
  tasks:
    - name: Configure Consul on Consul member nodes
      ansible.builtin.import_role:
        name: ../../roles/consul
      when: groups['all'] | length() > 1