# This task will check if Vault has been initialized and read the secrets from there if so
- name: Vault Status check
  hosts: local:hashi_servers
  tasks:
    - name: include vault role
      include_role:
        name: ../../roles/vault
        tasks_from: secrets
      when: ansible_local.vault is defined and ansible_local.vault.initialized == "true" and secrets_read is not defined

# This play only applies to the single server installation
- name: Configure containers for single installations
  hosts: local
  tasks:
    - name: include backend role
      include_role:
        name: ../../roles/backend
        tasks_from: single

# This play only applies to cluster installations
- name: Write cluster configuration
  hosts: hashi_servers
  tasks:
    - name: Include backend role
      include_role:
        name: ../../roles/backend
        tasks_from: cluster

- name: Write Nomad job
  hosts: backend_servers
  tasks:
    - name: Include nomad role
      include_role:
        name: ../../roles/nomad
        tasks_from: job
