# This task will check if Vault has been initialized and read the secrets from there if so
- name: Vault Status check
  hosts: local:hashi_servers
  tasks:
    - name: Include vault role
      include_role:
        name: ../../roles/vault
        tasks_from: secrets
      when: ansible_local.vault is defined and ansible_local.vault.initialized == "true" and secrets_read is not defined

- name: Deploy and configure MySQL database
  hosts: database_servers
  serial: 1
  tasks:
    - name: Include db role
      include_role:
        name: ../../roles/db
      when:
        - config_done is defined
        - mysql_host is not defined
        - groups['all'] | length() > 1
