---

# This task will check if Vault has been initialized and read the secrets from there if so
- name: Vault Status check
  hosts: local:hashi_servers
  tasks:
    - name: Include vault role
      include_role:
        name: ../../roles/vault
        tasks_from: secrets
      when: ansible_local.vault is defined and ansible_local.vault.initialized == "true" and secrets_read is not defined

- name: Include offline installation check
  hosts: docker_registry:backend_servers:voip_servers:management_servers:local
  tasks:
    - name: Import check offline installation task
      ansible.builtin.include_role:
        name: "{{ teamwire_platform_dir if teamwire_platform_dir is defined else (ansible_inventory_sources[0] | dirname)  }}/roles/common"
        tasks_from: check_offline_installation

- name: Deploy Docker (registry host)
  hosts: docker_registry
  roles:
    - role: ../../roles/docker

- name: Deploy Docker (non-registry hosts)
  hosts: backend_servers:voip_servers:management_servers:local:!docker_registry
  roles:
    - role: ../../roles/docker
