- hosts: local:management_servers
  roles:
  - role: ../../roles/management

- name: Install database backup & restore script
  hosts: local:management_servers
  tasks:
    - name: Include db role
      include_role:
        name: ../../roles/db
        tasks_from: backupscript

- name: Clean-up non-management servers
  hosts: all:!management_servers
  tasks:
    - name: Include management role
      include_role:
        name: ../../roles/management
        tasks_from: cleanup
      when: groups['all'] | length() > 1
