# This task will check if Vault has been initialized and read the secrets from there if so
- name: Vault Status check
  hosts: local:hashi_servers
  tasks:
    - name: include vault role
      include_role:
        name: ../../roles/vault
        tasks_from: secrets
      when: ansible_local.vault is defined and ansible_local.vault.initialized == "true" and secrets_read is not defined

- hosts: hashi_servers:backend_servers:management_servers:voip_servers:video_servers
  serial: 1
  tasks:
    - name: Deploy and configure the nomad role
      ansible.builtin.import_role:
        name: ../../roles/nomad
      when:
        - groups['all'] | length() > 1