- hosts: hashi_servers:local
  roles:
  - role: ../../roles/vault

- name: Run postfix tasks to configure email credentials after initial bootstrap
  hosts: all
  gather_facts: true
  tasks:
    - name: include common role
      include_role:
        name: ../../roles/common
        tasks_from: postfix
      when: new_vault_bootstrap is defined

- name: Distribute Vault token to all remaining hosts that require it
  hosts: all:!hashi_servers
  tasks:
    - name: Copy vault token
      copy:
        content: "{{ vault_token }}"
        dest: "{{ item.dest }}"
        mode: 0400
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
      with_items:
        - { dest: '/root/.vault-token', owner: 'root', group: 'root' }
        - { dest: '/home/teamwire/.vault-token', owner: 'teamwire', group: 'teamwire' }
      when: new_vault_bootstrap is defined and vault_token is defined and groups['all'] | length() > 1

- name: Distribute Vault SSL certificates to all remaining hosts that require them
  hosts: all:!hashi_servers
  tasks:
    - name: Copy Vault SSL certificates
      block:
        - name: Create Vault SSL directory
          file: path=/var/lib/vault/ssl mode=0750 state=directory
        - name: Install Vault root CA, tls certificate and private key
          copy:
            content: "{{ item.content }}"
            dest: "{{ item.dest }}"
          with_items:
            - { content: '{{ vault_certificate.data.issuing_ca }}', dest: '/usr/local/share/ca-certificates/vault-rootCA.crt' }
            - { content: '{{ vault_certificate.data.certificate }}', dest: '/var/lib/vault/ssl/vault.crt' }
            - { content: '{{ vault_certificate.data.private_key }}', dest: '/var/lib/vault/ssl/vault.pem' }
        - name: Trust the Vault Root CA
          command: update-ca-certificates
      when: new_vault_bootstrap is defined and vault_certificate is defined and groups['all'] | length() > 1
