# Please refer here: https://github.com/ansible/ansible/issues/30901 why `inventory_dir` is
# sometimes not possible to use
- hosts: local:management_servers
  roles:
  - role: "{{ ansible_inventory_sources[0] | dirname }}/roles/voip"
    when: enable_voip is defined and enable_voip | string() == 'true'

- hosts: voip_servers
  tasks:
  - import_tasks: "{{ ansible_inventory_sources[0] | dirname }}/roles/voip/tasks/voip_servers.yml"
    when: enable_voip is defined and enable_voip | string() == 'true'

- hosts: voip_servers
  tasks:
  - import_tasks: "{{ ansible_inventory_sources[0] | dirname }}/roles/backend/tasks/add_additional_host.yml"
    when: enable_voip is defined and enable_voip | string() == 'true'
