# This task will check if Vault has been initialized and read the secrets from there if so
- name: Vault Status check
  hosts: local:hashi_servers
  tasks:
    - include_role:
        name: ../../roles/vault
        tasks_from: secrets
      when: ansible_local.vault is defined and ansible_local.vault.initialized == "true" and secrets_read is not defined

# Please refer here: https://github.com/ansible/ansible/issues/30901 why `inventory_dir` is
# sometimes not possible to use
- hosts: local:management_servers
  roles:
    - role: "{{ ansible_inventory_sources[0] | dirname }}/roles/voip" # noqa internal-error
      when: enable_voip is defined and enable_voip | string() == 'true'

- hosts: voip_servers
  tasks:
    - import_tasks: "{{ ansible_inventory_sources[0] | dirname }}/roles/voip/tasks/voip_servers.yml"
      when: enable_voip is defined and enable_voip | string() == 'true' and groups['all'] | length == 1

- hosts: video_servers
  tasks:
    - import_tasks: "{{ ansible_inventory_sources[0] | dirname }}/roles/voip/tasks/voip_servers.yml"
      when: enable_voip is defined and enable_voip | string() == 'true' and groups['all'] | length  > 1

- hosts: voip_servers
  tasks:
    - import_tasks: "{{ ansible_inventory_sources[0] | dirname }}/roles/backend/tasks/add_additional_host.yml"
      when: enable_voip is defined and enable_voip | string() == 'true' and groups['all'] | length == 1

- hosts:  video_servers
  tasks:
    - import_tasks: "{{ ansible_inventory_sources[0] | dirname }}/roles/backend/tasks/add_additional_host.yml"
      when: enable_voip is defined and enable_voip | string() == 'true' and groups['all'] | length > 1
