---

- name: Generate Docker volume turnvol
  community.docker.docker_volume:
    name: turnvol

- name: Copy teamwire certificate
  ansible.builtin.copy:
    src: "{{ ssl_server_certificate }}"
    dest: "/var/lib/docker/volumes/turnvol/_data/teamwire.server.crt"
    mode: 0644
  notify: Trigger_turn_restart
  when: ssl_server_certificate is defined

<<<<<<< HEAD
- name: Copy certificate to turnvol
  command: docker cp /etc/ssl/certs/teamwire.server.crt teamwire_turn:/data

- name: Copy key to turnvol
  command: docker cp /etc/ssl/private/teamwire-backend.key teamwire_turn:/data

- name: Change permissions on certificate
  command: docker exec -t -u 0 teamwire_turn chmod 644 /data/teamwire.server.crt

- name: Cange permissions on key
  command: docker exec -t -u 0 teamwire_turn chmod 644 /data/teamwire-backend.key

- name: Remove  the temporarily Teamwire turn container
  docker_container:
    name: teamwire_turn
    image: "{{ LOCAL_REGISTRY | default() }}{{ 'harbor.teamwire.eu/' if use_teamwire_registry | default('true') | bool }}{{ VOIP_CONTAINER_TURN }}:{{ VOIP_JITSI_VERSION }}"
    state: absent
=======
- name: Copy the teamwire ssl key
  ansible.builtin.copy:
    src: "{{ ssl_keyfile }}"
    dest: /var/lib/docker/volumes/turnvol/_data/teamwire-backend.key
    mode: 0644
  notify: Trigger_turn_restart
  when: ssl_keyfile is defined
>>>>>>> 56d8d30 (Make sure ssl certificates on turn volume get updated)
