- name: Allow voip video bridge port
  ufw:
    rule: allow
    port: "10000"
    proto: any
  when: enable_voip is defined and enable_voip | string() == 'true'

- name: Copy tw_prosodyctl script.
  copy:
    src: ../files/tw_prosodyctl
    dest: "/usr/local/bin/tw_prosodyctl"
    mode: 0755
    owner: root
    group: root
  when: groups['all'] | length > 1 
  
- name: Add turns Firewall Rule allow 5349
  ufw:
    rule=allow
    port=5349
    proto=any
  when:
    - enable_stun is defined
    - enable_stun | string() == 'true'
    - inventory_hostname in groups["voip_servers"]
