---
- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: restart NTP
  service:
    name: ntp
    state: restarted

- name: reload sshd
  service:
    name: ssh
    state: reloaded

- name: rebuild postfix passwd map
  command: postmap /etc/postfix/sasl/passwd

- name: rebuild postfix generic map
  command: postmap /etc/postfix/generic

- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: new aliases
  command: newaliases

- name: rebuild postfix domain map
  command: postmap /etc/postfix/virtual

- name: reload dhclient
  command: pkill dhclient
  ignore_errors: true # noqa ignore-errors
  notify: reload dhclient step 2

- name: reload dhclient step 2
  command: dhclient
  ignore_errors: true # noqa ignore-errors

- name: reload systemd
  command: systemctl daemon-reload # noqa command-instead-of-module

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: true
