---
- name: Install GlusterFS server and client
  apt: name={{ item }}
  with_items:
    - glusterfs-server
    - glusterfs-client
    - rpcbind

- name: Create GlusterFS brick
  file:
    path: "{{ gluster_brick_dir }}"
    state: directory

- name: Start GlusterFS server
  service:
    name: glusterd
    state: started
    enabled: true

- name: Create Gluster volume "{{ gluster_volume }}"
  gluster_volume:
    name: "{{ gluster_volume }}"
    bricks: "{{ gluster_brick_dir }}"
    cluster: "{{ groups[glusterfs_peer_group] }}"
    replicas: "{{ groups[glusterfs_peer_group] | count }}"
    force: true
    state: present
  run_once: true

- name: Mount GlusterFS from localhost
  mount:
    name: /data
    src: "{{ inventory_hostname }}:{{ gluster_volume }}"
    fstype: glusterfs
    opts: defaults,_netdev,backupvolfile-server={{ groups[glusterfs_peer_group] | difference([inventory_hostname]) | first }}
    state: mounted
  when: inventory_hostname in groups[glusterfs_peer_group]
