---
- name: Install NFS server
  apt: name={{ item }} state=present
  with_items:
  - nfs-kernel-server
  - rpcbind
  notify: restart NFS server

- name: Create the NFS root directory
  file:
    name: /data
    state: directory

- name: Write the NFS config
  template:
    src: exports.j2
    dest: /etc/exports
  notify: reload NFS server
