- name: restart icinga2
  service: name=icinga2 state=restarted
  notify: restart apache

- name: restart nagios-nrpe-server
  service: name=nagios-nrpe-server state=restarted

- name: restart apache
  service: name=apache2 state=restarted

- name: update apt
  ansible.builtin.apt:
    update_cache: yes