---
# Remove gitwrapper and git pinning feature
- include_tasks: gitwrapper.yml
  when: groups['all'] | length() == 1 or inventory_hostname in groups['management_servers']

# Remove APT repository signing keys from global trust anchor
- include_tasks: apt_signing_keys.yml

# Remove unneeded packages
- include_tasks: apt_packages.yml

# Remove docker process list
- name: Clean docker processes.
  include_tasks: clean_docker_process_list.yml
