# Keep track of the plattform repository
- name: Install git
  apt: pkg=git state=present

- name: Check out the teamwire/platform git repository
  git: # noqa git-latest
    repo: https://github.com/teamwire/platform.git
    depth: 1
    dest: /home/teamwire/platform
    update: false
  notify: fix ownership of git checkout

- name: Check config file status
  stat: path=/home/teamwire/platform/ansible/group_vars/all
  register: config_file

- name: Secure permissions of Ansible configuration file
  file:
    path: /home/teamwire/platform/ansible/group_vars/all
    state: file
    mode: 0600
    owner: teamwire
    group: teamwire
  when: config_file.stat.exists

- name: Install the container helper tool
  copy: src=../../roles/management/files/twctl dest=/usr/local/bin/twctl mode=0755 owner=root group=root

- name: Install new motd
  copy:
    src: motd.sh
    dest: /etc/motd.sh
    owner: root
    group: root
    mode: 0755
  when:
    - not offline_mode.stat.exists
    - enableMOTD

- name: stat original motd
  stat:
    path: /etc/motd
  register: motd_stat

- name: Deactivate old motd
  command: mv /etc/motd /etc/motd.deactivate
  when: motd_stat.stat.exists

- name: Test if line motd exists in global profile
  shell: grep '/etc/motd.sh' /etc/profile # noqa command-instead-of-shell
  register: grep_motd
  failed_when: grep_motd.rc >= 2
  when: not offline_mode.stat.exists

- name: Activate new motd when not exists
  lineinfile:
    dest: /etc/profile
    line: "/etc/motd.sh"
  when:
    - not offline_mode.stat.exists
    - grep_motd.rc == 1
    - enableMOTD

- name: Deactivate new motd if not enabled
  lineinfile:
    dest: /etc/profile
    line: "/etc/motd.sh"
    state: absent
  when:
    - not offline_mode.stat.exists
    - not enableMOTD

- include: backup.yml
  when: config_done is defined
