NGINX_HTTP_PORT: 7080
NGINX_HTTPS_PORT: 7443

VOIP_ROOT_PATH: "/data/voip"
VOIP_JITSI_VERSION: "stable-5963"


VOIP_CONTAINER_WEB: "teamwire/web2"
VOIP_CONTAINER_PROSODY: "teamwire/prosody"
VOIP_CONTAINER_JICOFO: "teamwire/jicofo"
VOIP_CONTAINER_JVB: "teamwire/jvb"

nomad_health_voip_interval: 15
nomald_health_voip_timeout: 2
