---
# This playbook procedure will renew a Vault certificate, whether it's expired or not and place the certificate and key at the relevant locations

- name: Renew Vault SSL certificate
  hosts: all
  tasks:
    - name: Include vault vars yaml
      ansible.builtin.include_vars: ../../roles/vault/defaults/main.yml

    - name: Include group vars
      ansible.builtin.include_vars: "{{ inventory_dir }}/group_vars/all"

    - name: Check Vault seal status
      ansible.builtin.fail:
        msg: "Vault is not in an unsealed state, please run 'twctl secrets unseal'."
      when: ansible_local.vault.sealed != "false"

    - name: Issue a TLS certificate for Vault to use
      ansible.builtin.command: vault write -tls-skip-verify pki/issue/tls common_name="127.0.0.1" alt_names=""{{ groups['hashi_servers'] | map('extract', hostvars, ['inventory_hostname']) | join(',') + ',' if groups['all'] | length() > 1 else '' }}"localhost,*.node.dc1.consul,*.vault.service.dc1.consul,vault.service.consul" ip_sans=""{{ groups['hashi_servers'] | map('extract', hostvars, ['private_ip']) | join(',') + ',' if groups['all'] | length() > 1 else '' }}"127.0.0.1" ttl="{{ vault_certificate_ttl }}" --format=json
      run_once: true
      register: issue_info
      when: groups['all'] | length() == 1 or groups['all'] | length() > 1 and inventory_hostname in groups['hashi_servers']

    - name: Set certificate fact
      run_once: true
      ansible.builtin.set_fact:
        vault_certificate: "{{ issue_info.stdout | from_json }}"

    - name: Install Vault root CA, tls certificate and private key
      ansible.builtin.copy:
        content: "{{ item.content }}"
        dest: "{{ item.dest }}"
        user: root
        group: root
        mode: '0644'
      with_items:
        - {
            content: "{{ vault_certificate.data.certificate }}",
            dest: "/var/lib/vault/ssl/vault.crt",
          }
        - {
            content: "{{ vault_certificate.data.private_key }}",
            dest: "/var/lib/vault/ssl/vault.pem",
          }
      become: true

    - name: Restart Nomad to recognise SSL renewal
      ansible.builtin.service:
        name: nomad
        state: restarted
      when: groups['all'] | length() > 1 and inventory_hostname in groups.hashi_servers | union(groups.backend_servers)

    - name: Restart Vault to recognise SSL renewal
      ansible.builtin.service:
        name: vault
        state: restarted
      when: groups['all'] | length() == 1 or groups['all'] | length() > 1 and inventory_hostname in groups['hashi_servers']

    - name: Vault certificate info
      ansible.builtin.debug:
        msg:
          - "The Vault SSL certificate has now been renewed and is valid for 2 years, this procedure may be re-run at any point"
          - "IMPORTANT: Vault must be unsealed via twctl secrets unseal"
          - "The unseal operation must be performed twice to fully unlock Vault and if on a cluster system, this will need to be performed on all hosts in the hashi_servers group" # noqa line-length
          - "If you encounter any issues, please email support@teamwire.eu"
      run_once: true
