---
- name: reload systemd
  command: systemctl daemon-reload # noqa command-instead-of-module

- name: reload haproxy
  service: name=haproxy state=reloaded

- name: restart haproxy
  systemd: daemon_reload=yes name=haproxy state=restarted enabled=yes

- name: restart Consul Template
  service: name=consul-template state=restarted
