---

- name: Import requirements which needs to run first
  import_playbook: requirements.yml

- name: Ask for additional information upfront
  hosts: hashi_servers:local
  tasks:
    - name: Ask for additional information
      include_role:
        name: "{{ inventory_dir }}/roles/vault"
        tasks_from: gather_information.yml

- include: roles/common.yml
- include: roles/management.yml
- include: roles/consul.yml
- include: roles/vault.yml
- include: roles/storage_servers.yml
- include: roles/storage_client.yml
- include: roles/database_servers.yml
- include: roles/backend.yml
- include: roles/nomad.yml
- include: roles/container.yml
- include: roles/loghost.yml
- include: roles/docker.yml
- include: roles/voip.yml
- include: roles/go.yml
- include: roles/redis_servers.yml
- include: roles/frontend.yml
- include: roles/load_balancers.yml
- include: roles/monitoring.yml
- include: roles/housekeeping.yml


- name: Set current tag (COMPLETE) in /etc/platform_version
  hosts: all
  tasks:
  - copy:
      dest: /etc/platform_version
      content: "{{ current_local_tag }}"
      owner: root
      group: root
      mode: 0644
    when: packer_build_name is not defined
