---
- include_tasks: configuration.yml

- name: Create cluster config directory
  file: dest=/data/cluster_config state=directory mode=0770 owner=root group=teamwire
  run_once: true

- name: Write cluster configuration file
  run_once: true
  template:
    src: ../../roles/backend/templates/cluster.conf.j2
    dest: /data/cluster_config/cluster.conf
    mode: 0640
    owner: root
    group: teamwire

- name: Log into Harbor and force re-authorization
  docker_login:
    registry: harbor.teamwire.eu
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"
    reauthorize: yes
  become: yes
  become_user: teamwire
  delegate_to: localhost
  run_once: true
  when:
    - use_teamwire_registry | default('true') | bool
