---
- name: reload systemd
  command: systemctl daemon-reload

- name: restart MariaDB
  service: name=mysql state=restarted

- name: restart consul
  service: name=consul state=restarted

- name: running config
  command: mysql -e "SET GLOBAL innodb_buffer_pool_size=({{ innodb_buffer_size.stdout_lines[1] | int }} * 1024 * 1024 * 1024);"
  become: true