---
- name: reload systemd
  command: systemctl daemon-reload # noqa command-instead-of-module

- name: restart MariaDB
  service: name=mysql state=restarted

- name: restart consul
  service: name=consul state=restarted

- name: set innodb in runtime
  command: mysql -e "SET GLOBAL innodb_buffer_pool_size=({{ innodb_buffer_pool_size }} * 1024 * 1024 * 1024);"
  become: true

- name: set optimizer in runtime
  command: mysql -e "SET GLOBAL optimizer_search_depth={{ optimizer_search_depth_value }};"
  become: true
