---
# Some credentials shouldn't be stored as plain variables thus they're asked for interactively
# In case this role is executed outside of the overall Teamwire platform playbook
# they've already been asked at the very beginning
- name: Ask for additional information
  block:

    - name: Ask for credentials
      block:
        - name: Ask for container registry password
          block:
            - name: Container registry password required
              pause:
                prompt: "Please enter the password for {{ dockerhub_username }}"
                echo: no
              register: pause_entry
            - name: Save container registry password
              set_fact:
                dockerhub_password: "{{ pause_entry.user_input }}"
              when: pause_entry.user_input is defined
          when: dockerhub_password is undefined

        - name: Ask for Firebase Cloud Messaging (FCM) API key
          block:
            - name: Google API key required
              pause:
                prompt: "Please enter the key you have received from us"
                echo: no
              register: pause_entry
            - name: Save container registry password
              set_fact:
                gcm_api_key: "{{ pause_entry.user_input }}"
              when: pause_entry.user_input is defined
          when: gcm_api_key is undefined

        - name: Ask for SMTP authentication details
          block:
            - name: SMTP authentication
              pause:
                prompt: "Does your SMTP server require password authentication? (yes/no)"
              register: smtp_smartpass_required
            - name: SMTP password required
              pause:
                prompt: "SMTP password required. Please enter the password for {{ smtp_smartuser }}"
                echo: no
              register: pause_entry
              when:
                - smtp_smartpass_required.user_input is defined
                - ('yes' in smtp_smartpass_required|lower) or
                  ('y' in smtp_smartpass_required|lower)
            - name: Save SMTP password
              set_fact:
                smtp_smartpass: "{{ pause_entry.user_input }}"
              when: pause_entry.user_input is defined
          when: smtp_smartpass is undefined

        - name: Ask for external database password
          block:
            - name: Password required for external Teamwire database
              pause:
                prompt: "Please enter the password for {{ teamwire_db_user }}"
                echo: no
            - name: Save database password
              set_fact:
                teamwire_db_password: "{{ pause_entry.user_input }}"
              when: pause_entry.user_input is defined
          when: (mysql_host is defined and teamwire_db_password is undefined) or
                (oracle_host is defined and teamwire_db_password is undefined)

        - name: Ask for existing AES key
          block:
            - name: Use existing AES key
              pause:
                prompt: "Would you like to use an AES key from an existing installation? (yes/no)"
                echo: yes
              register: aes_confirm
            - name: Database AES key required
              pause:
                prompt: "Please enter the AES key from your previous installation"
                echo: no
              register: pause_entry
              when:
                - aes_confirm.user_input is defined
                - ('yes' in aes_confirm|lower) or
                  ('y' in aes_confirm|lower)
            - name: Save AES key
              set_fact:
                aes_key: "{{ pause_entry.user_input }}"
              when: pause_entry.user_input is defined
          when: aes_key is undefined
      when: ansible_local.vault is defined and ansible_local.vault.initialized != "true"

    - name: Remember that information have been asked for
      set_fact:
        vault_user_input_performed: yes

  when: not vault_user_input_performed | default('no') | bool