---
- name: Check if Vault is already installed
  stat: path=/usr/local/bin/vault
  register: vault_binary

- name: Create 3rd party download directory
  file:
    dest: /var/cache/downloads
    state: directory
    mode: 0755

- name: Download Vault
  get_url:
    url: https://releases.hashicorp.com/vault/{{vault_version}}/vault_{{vault_version}}_linux_amd64.zip
    dest: /var/cache/downloads/vault_{{vault_version}}_linux_amd64.zip
    checksum: sha256:{{vault_checksum}}
    mode: 0440
    use_proxy: '{{ "yes" if http_proxy is defined else omit }}'
  register: vault_downloaded
  environment:
    https_proxy: "{{ http_proxy|default() }}"

- name: Create Vault user
  user:
   name: vault
   shell: /usr/sbin/nologin
   system: true
   home: /var/lib/vault
   state: present

- name: Change audit log permission
  file:
    path: /var/log/vault_audit.log
    owner: vault
    group: vault
    state: touch
    mode: 0600

- name: Install logrotate job for vault
  copy:
    src: vault-log
    dest: /etc/logrotate.d/vault-log

- name: Install the Vault binary
  unarchive:
    src: /var/cache/downloads/vault_{{vault_version}}_linux_amd64.zip
    dest: /usr/local/bin
    mode: 0755
    copy: no
  notify: Restart Vault
  when: vault_downloaded.changed or not vault_binary.stat.exists

- name: Create Vault directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: vault
    group: vault
  with_items:
    - /etc/vault
    - /var/lib/vault
    - /var/lib/vault/ssl
    - /var/lib/vault/store

- block:
    - name: Check if Vault certificates exist and are valid
      openssl_certificate:
        path: /var/lib/vault/ssl/vault.crt
        provider: assertonly
        has_expired: no
  rescue:
    - debug: msg="Generating SSL certificates for Vault"
    - include: ssl-setup.yml
  when: ansible_local.vault is defined and ansible_local.vault.initialized == "true"

- name: Write Vault config
  template:
     src: vault.hcl.j2
     dest: /etc/vault/vault.hcl
     owner: vault
     group: vault
  notify: Restart Vault

- name: Vault systemd config
  copy:
    src: vault.service
    dest: /etc/systemd/system/vault.service
  notify:
    - Restart Vault

- name: Enable the Vault service
  service:
    name: vault
    state: started
    enabled: yes
    daemon_reload: yes

# Handlers should be flushed before any possible bootstrapping
- meta: flush_handlers

- name: Bootstrap Vault on new installations
  include_tasks: bootstrap.yml
  when: ( vault_bootstrap_procedure is not defined and config_done is defined and disable_vault is defined and disable_vault| lower() != "true" and ansible_local.vault is defined and ansible_local.vault.initialized != "true" ) or
        ( vault_bootstrap_procedure is not defined and config_done is defined and disable_vault is not defined and ansible_local.vault is defined and ansible_local.vault.initialized != "true" )
