- name: Unseal Vault
  command: vault operator unseal "{{ item }}"
  no_log: true
  with_items:
    - "{{ unseal_key1 }}"
    - "{{ unseal_key2 }}"
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"

- name: Issue a TLS certificate for Vault to use
  command: vault write pki/issue/tls common_name=127.0.0.1 ip_sans="127.0.0.1" --format=json
  run_once: True
  register: issue_info
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"

- name: Set certificate fact
  run_once: True
  set_fact:
    vault_certificate: "{{ issue_info.stdout | from_json }}"

- name: Install Vault tls certificate and private key
  copy: content={{ item.content }} dest={{ item.dest }}
  with_items:
    - { content: '{{ vault_certificate.data.certificate }}', dest: '/var/lib/vault/ssl/vault.crt' }
    - { content: '{{ vault_certificate.data.private_key }}', dest: '/var/lib/vault/ssl/vault.pem' }
  become: yes

- name: Restart Vault so that it uses TLS
  service:
    name: vault
    state: restarted
