---
- name: Create Docker Registry storage directory
  file: name="{{ registry_dir }}" state=directory mode=0750
  run_once: true

- name: Write Docker registry config file
  template: src="{{ registry_config }}" dest="{{ registry_dir }}/config.yml"
  run_once: true
  notify: restart registry container

- name: Retrieve the  Docker Registry container
  when: config_done is defined
  docker_image:
    name: "{{ registry_version }}"
    source: pull
    state: present

# Push all local images to the local registry
- name: Copy the registry image helper tool
  copy: src=twimg dest=/usr/local/bin/ mode=0755
