---
- name: Import requirements which needs to run first
  import_playbook: playbooks/requirements.yml

- name: Apply common configuration to all nodes
  hosts: all
  roles:
    - common
    - management

- name: Deploy and configure external storage client
  hosts: all
  roles:
    - { role: storage_client, when external_storage_path is defined }

- name: Deploy Vault secret system
  hosts: all
  roles:
    - { role: vault, when: config_done is defined }

- name: Deploy and configure MySQL database
  hosts: all
  roles:
    - { role: db, when: config_done is defined and mysql_host is not defined and oracle_host is not defined }

- name: Deploy and configure Redis database
  hosts: all
  roles:
    - { role: redis, when: config_done is defined }

- name: Deploy and configure the backend server
  hosts: all
  roles:
    - docker
    - { role: backend, when: config_done is defined }
    - { role: voip, when: config_done is defined and enable_voip is defined and enable_voip | string() == 'true' }
    - { role: go, when: config_done is defined }
    - { role: frontend, when: config_done is defined }

- name: Deploy monitoring services
  hosts: all
  roles:
    - { role: monitoring, when: config_done is defined and enable_monitoring is defined }

- name: Run housekeeping job to remove unused dependencies
  hosts: all
  roles:
    - { role: housekeeping, when: config_done is defined }

- name: Set current tag (COMPLETE) in /etc/platform_version
  hosts: all
  tasks:
  - copy:
      dest: /etc/platform_version
      content: '{{ current_local_tag }}'
      owner: root
      group: root
      mode: 0644
    when: packer_build_name is not defined
