---
- name: reload systemd
  command: systemctl daemon-reload # noqa command-instead-of-module

- name: restart redis
  service: name=redis-server state=restarted

- name: reload consul
  command: consul reload
